### PR TITLE
feat: UI Improvement- add start buttons on PR events cards

### PR DESCRIPTION
**Pull request by ombharatiya**
## Context

For events Start button for creating a new event should be displayed separately from the Stop button which is applicable for a specific event.

## Objective

- Show Stop button on Event cards when event is in progress.
- Add Start/Stop button on PR Events cards.
- Remove Stop button from event graph area(event header).
- Remove Start button when PR tab is selected.

## References

https://github.com/screwdriver-cd/screwdriver/issues/2516

https://github.com/screwdriver-cd/screwdriver/issues/2502

https://github.com/screwdriver-cd/screwdriver/issues/2298

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by ombharatiya** [comment]
Some Screenshots for review:

Screenshot 2021-08-21 at 4 46 34 AM
Screenshot 2021-08-21 at 4 47 18 AM

**Comment by jazminorozco** [comment]
Looks great, I'm wondering what the button on the selected card would look like if it didn't have a white background though. Looks a bit odd to have the white on the blue.

**Comment by ombharatiya** [comment]
In this attached screenshot, you can see how the Start button looks like when 1st card is selected:

Screenshot 2021-08-22 at 4 53 41 AM

I think it looks good. Here's the screenshot when hovered on the card:

Screenshot 2021-08-22 at 4 55 13 AM

Looks standard to me.

**Review by adong — APPROVED** [review]
Looks good to me.

**Pull request merged**
