### PR TITLE
fix(2227): restrict user interaction for builds that in CREATED status

### PR DESCRIPTION
**Pull request by adong**
## Context

See issue https://github.com/screwdriver-cd/screwdriver/issues/2227 on how to reproduce it.

image

## Objective

<details><summary>
<i>Original Thought</i>
</summary>
<p>

I have put in `RUNNING` state, because to me `CREATED` seems to be running, maybe we should change state from _CREATED_ to _QUEUED_ 🤔? 

image

image
</p>
</details>

<details><summary>New Apporach</summary>
<p>

* make users not able to go to build details page in workflow graph
* ~make users not able to go to build details page in job list view~
* do not show builds in CREATED status in job list view

</p>
</details>

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by jithine — CHANGES_REQUESTED** [review]
`Created` is not running, builds in `created` status should be hidden in UI in a sens that workflow graph should not allow navigation to that build detail page

**Comment by tkyi** [comment]
Will status still say CREATED on event banner?

**Comment by jithine** [comment]
> Will status still say CREATED on event banner?

maybe we can map `CREATED` event status to Waiting/Running ? @adong @tkyi

**Comment by adong** [comment]
> Will status still say CREATED on event banner?

Yes, that remains. Users just not be able to click to build details page

**Comment by adong** [comment]
> > Will status still say CREATED on event banner?
> 
> maybe we can map `CREATED` event status to Waiting/Running ? @adong @tkyi

I think I'd rather show as-is. So we can see the payload value `CREATED` on the UI, it's consistent, and would be easier to debug.

**Comment by jithine** [comment]
> I think I'd rather show as-is. So we can see the payload value CREATED on the UI, it's consistent, and would be easier to debug.

@adong  event does not have a status. UI is parsing build status to display overall status. I think logic should be tweaked to give prefrence to `RUNNING` status over `CREATED`.
ie if there are builds in both `RUNNING` & `CREATED` status, it should say `RUNNING` as event status. 
now if there is only one build is `CREATED` status, we are talking about the overall status of event, which doesn't have any status of it's own. I think it's better to show event as `RUNNING ` even in this case because technically event is still active.

**Comment by adong** [comment]
Rebased with latest master

**Review by jithine — APPROVED** [review]

**Pull request merged**
