### PR TITLE
Revert "feat(2346): Support for job level parameters (#754)"

### PR DESCRIPTION
**Pull request by esuc4se**
## Context
Since the tooltip is not displayed due to the change of https://github.com/screwdriver-cd/ui/pull/754, revert it.

## Objective
The most recent UI changes were:
* https://github.com/screwdriver-cd/ui/pull/754
* https://github.com/screwdriver-cd/ui/pull/757

When I investigated in the local environment, the commit by https://github.com/screwdriver-cd/ui/pull/754 was the cause of the tooltip not being displayed.
It's not good if the tooltip isn't displayed, so let me revert your changes.

In the investigation, I reverted the commits https://github.com/screwdriver-cd/ui/pull/754 and https://github.com/screwdriver-cd/ui/pull/757 respectively to see which commit was the cause and whether it happened accidentally due to both changes.

## License
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by tk3fftk — APPROVED** [review]
LGTM

**Comment by adong** [comment]
Could this be a false alarm? I'm not sure which **tooltip**s are referenced here.

Example pipeline: https://cd.screwdriver.cd/pipelines/8143/

image

image

image

**Comment by tk3fftk** [comment]
@adong thank you for your checking.
for example, this pipeline is not working. tooltip means a panel when clicking bubbles (nodes) on workflow.
https://cd.screwdriver.cd/pipelines/1/events/658872

```
screwdriver-ui-46a0403334037fcdc1ea404b6f4ca929.js:691 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at n.graphClicked (screwdriver-ui-46a0403334037fcdc1ea404b6f4ca929.js:691)
    at e.n._run (vendor-4884634ca505955b915d5a820be37341.js:4287)
    at e.n._join (vendor-4884634ca505955b915d5a820be37341.js:4286)
    at e.n.join (vendor-4884634ca505955b915d5a820be37341.js:4252)
    at d (vendor-4884634ca505955b915d5a820be37341.js:3123)
    at vendor-4884634ca505955b915d5a820be37341.js:1497
    at a (vendor-4884634ca505955b915d5a820be37341.js:3040)
    at vendor-4884634ca505955b915d5a820be37341.js:1497
    at n.buildClicked (screwdriver-ui-46a0403334037fcdc1ea404b6f4ca929.js:796)
```

**Comment by sagar1312** [comment]
Found the root cause. Pushing the fix in this PR https://github.com/screwdriver-cd/ui/pull/759

**Comment by adong** [comment]
@esuc4se 
I just merged the PR, and let's see if that fixes the issue on your end.

**Comment by jithine** [comment]
issue has been fixed, this PR is not needed

**Pull request closed without merging**
