### PR TITLE
feat: Add Start/Stop Button in PR list view

### PR DESCRIPTION
**Pull request by ombharatiya**
## Context

We triggered a PR build once manually (due to restrictPR) using the "Start" button. After the build has completed, more changes were pushed. However, the "start" button disappeared, so triggering the build required clicking through to the pull-request event, and clicking "restart" on top right.

Start/Stop buttons are missing for Pull Requests and is shown only for chainPR use case. 

Also build control view when Pull req tab is selected creates confusion, since it is only relevant for event tab.

## Objective

1. For Pull Requests Start/Stop button should be displayed next to the PR where it's applicable.
2. Hide build control view on Pull req tab selection

## References

https://github.com/screwdriver-cd/screwdriver/issues/2516 Point 1

https://github.com/screwdriver-cd/screwdriver/issues/2502

https://github.com/screwdriver-cd/screwdriver/issues/2298

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by ombharatiya** [comment]
Preview

Before change:
Screenshot 2021-07-23 at 11 30 54 PM

After Change:
Screenshot 2021-07-23 at 11 12 45 PM

**Comment by jazminorozco** [comment]
@adong Is the "after change" screenshot the proposal for where to position the start button? If so I think that placement works. It's where I was going to suggest it be placed.

**Comment by tkyi** [comment]
When on the pull request tab, should we hide the Start button for the latest commit?

**Comment by ombharatiya** [comment]
Screenshot of the new changes:

1. Start Button on every pr card at the top right corner after the title
2. Having a stop button to stop the build after it starts running
3. Hide build control view on Pull req tab click 

Screenshot 2021-08-03 at 2 22 00 AM

**Review by adong — APPROVED** [review]
Looks good to me for PR list view:

Screenshots: 
image

image


Stop button:
image



ChainPR still has the old behavior, I guess it's okay:
image


and we can improve the stop button on the event list next:
image


Approved.

**Review by jithine — APPROVED** [review]
👍 looks good. Is the view same when `restrictPr` is on ?

Also we should modift chainPR to have same behavior

**Pull request merged**
