### PR TITLE
feat(2878): add support for displaying user defined warnings

### PR DESCRIPTION
**Pull request by klu909**
## Objective

Screenshot 2023-05-30 at 9 39 37 AM
Screenshot 2023-05-30 at 9 38 56 AM
Screenshot 2023-05-30 at 9 38 42 AM

## References
https://github.com/screwdriver-cd/screwdriver/issues/2878

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by tkyi — APPROVED** [review]

**Comment by yakanechi** [comment]
@klu909 @tkyi 
Is it a specification that the meta parameter that displays warn and text is different from the meta parameter that sets the status of the warning?

The following two parameters needed to be set to reflect all of my testing at hand.
```
  steps:
    - warning: meta set build.warning "1"
    - alert: meta set meta.warning.foo "this is a foo"
```

**Comment by yakanechi** [comment]
This [PR](https://github.com/screwdriver-cd/launcher/pull/454) has been updated so that `build.warning` is not passed on to subsequent jobs.
On the other hand, the `meta.warning.foo` is being passed on to subsequent jobs.

**Comment by jithine** [comment]
@klu909 @tkyi looks like we don't have these `build.warning` & `meta.warning.` documented anywhere 

@yakanechi do you have a sample build we can look at  ?

**Comment by klu909** [comment]
> @klu909 @tkyi Is it a specification that the meta parameter that displays warn and text is different from the meta parameter that sets the status of the warning?
> 
> The following two parameters needed to be set to reflect all of my testing at hand.
> 
> ```
>   steps:
>     - warning: meta set build.warning "1"
>     - alert: meta set meta.warning.foo "this is a foo"
> ```

it's an oversight, build.meta.meta was changed in favour of build.meta.build because of metadata inheriting issue addressed in [pr](https://github.com/screwdriver-cd/launcher/pull/454). opened a new [pr](https://github.com/screwdriver-cd/ui/pull/950) to fix this

**Pull request merged**
