### PR TITLE
fix(2390): Add Validation on Create New Collection modal

### PR DESCRIPTION
**Pull request by kprasadpvv**
## Context

- Enable `Create` button only when mandatory fields are filled (i.e., `Name`)
- Adds mandatory marker for the `Name` field
- Renamed `Save` button label to `Create` to align UX with the work flow
- Re-order `Cancel` and `Create` buttons to follow remaining screens in the application
- Right aligned the buttons in the footer

## Objective

- To maintain better UX.

## References

https://github.com/screwdriver-cd/screwdriver/issues/2390

**ScreenShots:**

-Create Disable:
collection_create_disable

-Create Enable:
CreateEnable

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by tkyi** [comment]
Hi 👋 thanks for contributing to Screwdriver!
Can you adjust your pull request title to match this format: https://docs.screwdriver.cd/about/contributing/index

**Comment by kprasadpvv** [comment]
> Hi 👋 thanks for contributing to Screwdriver!
> Can you adjust your pull request title to match this format: https://docs.screwdriver.cd/about/contributing/index

Thanks @tkyi , i've updated the title.please review and let me know if more info is needed.

**Comment by tkyi** [comment]
Updated the title as an example of the syntax expected
Just for this package we're using to help with auto versioning

**Review by tkyi — APPROVED** [review]

**Comment by adong** [comment]
Test failed

image

**Comment by kprasadpvv** [comment]
> Test failed
> 
> image

Fixed the failing test.

**Review by tkyi — APPROVED** [review]
Thank you!

**Pull request merged**
