### PR TITLE
fix: Add the latestCommit marker to pipeline-graph-nav

### PR DESCRIPTION
**Pull request by wahapo**
## Context
If user select the latestCommit event, mark the SHA of `pipeline-graph-nav` to indicate that it is the latestCommit event.

## Objective
In the event list, the latestCommit is shown with a blue background, and the pipeline-graph-nav will show the same mark.

## References
The `.status` class in CSS resets each parameter because we don't want [them](https://github.com/screwdriver-cd/ui/blob/457f2c1cf18b8a870cf7f380d6366eaaadb2bbbd/app/styles/column-view.scss#L44-L48) to be used.
https://github.com/screwdriver-cd/ui/pull/717/files#diff-c77f1fdf1df50bb4b96a45c80dcd5838d188057a59650a0a25dd187762215425R16-R21

https://github.com/screwdriver-cd/screwdriver/issues/2168
https://github.com/screwdriver-cd/ui/pull/654

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by yoshwata — APPROVED** [review]

**Review by ibu1224 — APPROVED** [review]

**Review by itleigns — APPROVED** [review]

**Review by kumada626 — APPROVED** [review]

**Comment by wahapo** [comment]
@jithine @adong Please check this PR:pray: Thanks!

**Review by adong — APPROVED** [review]

**Comment by adong** [comment]
Looks good to me, merged.

**Comment by jithine** [comment]
@wahapo This seems to be adding a blue hover to entire pipeline header. 

Screen Shot 2021-06-08 at 11 22 26 AM

**Comment by wahapo** [comment]
@jithine Thank you, I fixed it.
https://github.com/screwdriver-cd/ui/pull/721

**Pull request merged**
