### PR TITLE
fix(715): Catch error message on the secrets page

### PR DESCRIPTION
**Pull request by wahapo**
## Context
I want fixed this issue.
https://github.com/screwdriver-cd/screwdriver/issues/715

## Objective
It displays errors, as shown in the screenshot below.

## References
The cause was that an exception was occurring [here](https://github.com/screwdriver-cd/ui/blob/44691e60419488c24fc17438dd5d987f1ee8b371/app/pipeline/secrets/route.js#L21), but we wasn't catch. The same goes for [secrets](https://github.com/screwdriver-cd/ui/blob/44691e60419488c24fc17438dd5d987f1ee8b371/app/pipeline/secrets/route.js#L16).

I'm not sure how to write a test in this case.

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by adong** [comment]
> I'm not sure how to write a test in this case.

Just write a unit test let `this.set('secrets') = RSVP.reject()` and verify the `this.errorMessage` is the `errorMessage` that supposed to be.

**Comment by adong** [comment]
After I take a look. Could you try add `error` action in `app/pipeline/secrets/route.js` instead? See, 
```
  actions: {
    error(error) {
      // if error.errors[0].detail is the error messages
	  this.controllerFor('pipeline.secrets').set('errorMessage', error.errors[0].detail);

      return true;
    }
 }
```

https://github.com/screwdriver-cd/ui/blob/44691e60419488c24fc17438dd5d987f1ee8b371/app/pipeline/events/show/route.js#L73-L79 as example 

Ref: https://guides.emberjs.com/v3.16.0/routing/loading-and-error-substates/#toc_the-error-event

**Comment by adong** [comment]
Actually, maybe just this to `app/pipeline/secrets/route.js`?

```javascript
    return this.store
      .findAll('token', { adapterOptions: { pipelineId: pipeline.get('id') } })
      .then(tokens => ({
        tokens,
        secrets,
        pipeline
      })).catch((error) => {
        this.controllerFor('pipeline.secrets').set('errorMessage', error.errors[0].detail); // <-
      });
```

image

**Comment by wahapo** [comment]
Oh, it's great, it's going to work.

**Review by adong — APPROVED** [review]

**Comment by jithine** [comment]
👏 Thank you for fixing this.

**Pull request merged**
