### PR TITLE
fix: Pipeline search panel UX

### PR DESCRIPTION
**Pull request by banusha2**
## Context
When adding multiple pipelines to a collection from Collection page does not display branch and source path info.
current:
Screen Shot 2022-09-20 at 11 44 54 AM

## Objective
Expectation:
Screen Shot 2022-09-22 at 10 38 52 AM

## References
https://github.com/screwdriver-cd/screwdriver/issues/2765

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by adong** [comment]
For some reason, I think the new layout looks more crowded than the old one.

**Comment by jithine** [comment]
> For some reason, I think the new layout looks more crowded than the old one.

we need to increase the overall modal size ?

**Comment by banusha2** [comment]
> > For some reason, I think the new layout looks more crowded than the old one.
> 
> we need to increase the overall modal size ?

yes. Is the content of the modal fine?

**Comment by jithine** [comment]
@banusha2 yes content is fine

**Review by jithine — APPROVED** [review]

**Pull request merged**
