### PR TITLE
fix(2065): fix workflow tooltip to make it easier to remove

### PR DESCRIPTION
**Pull request by esuc4se**
## Context
Modify SCSS so that workflow tooltips can be easily removed.

## Objective
Previously it could be deleted by clicking on the yellow area.
スクリーンショット 2021-11-25 15 51 38

This fix expands the area where tooltips can be removed.
スクリーンショット 2021-11-25 15 51 59

## References
https://github.com/screwdriver-cd/screwdriver/issues/2065

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by yuichi10 — APPROVED** [review]

**Review by sugarnaoming — DISMISSED** [review]

**Review by kkisic — APPROVED** [review]

**Comment by tk3fftk** [comment]
Do we also need fixing a workflow on pipeline-visualizer page?

**Comment by esuc4se** [comment]
@tk3fftk 
Also fixed the pipeline-visualizer page.

**Review by tk3fftk — APPROVED** [review]
:+1:

**Review by sugarnaoming — COMMENTED** [review]
👍

**Review by adong — APPROVED** [review]

**Pull request merged**
