### PR TITLE
feat:display build date/time

### PR DESCRIPTION
**Pull request by banusha2**
## Context

To find a specific build for a specific job in a very large pipeline, click on "jobs" view to get a recent list of builds for each job and hover over the green/red circles, build number visible which is not meaningful to a user.
## Objective
To display build date/time.
Screenshot 2023-03-15 at 11 31 15 AM

## References

https://github.com/screwdriver-cd/screwdriver/issues/2774
## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by adong** [comment]
Please add tests, otherwise looks good to me.

**Comment by adong** [comment]
Facing some weird issue on dates, so we might just use `containsText` instead exact match `hasText`
image

**Comment by adong** [comment]
Aha, it's because the moment is using local time by default, and our CI server has a different timezone. 

Local Mac 
```
$ date +"%Z %z"
PDT -0700
```

Remote CI:
```
$ date +"%Z %z"
20:31:25 UTC +0000
```

**Comment by jithine** [comment]
can the text in the tooltip be left aligned ?

**Pull request merged**
